site:
  title: SUSE® Rancher Manager
  url: /
  start_page: v2.13@rancher-manager:en:about-rancher/what-is-rancher.adoc
  robots: disallow
content:
  sources: 
  - url: .
    branches: HEAD
    start_paths: [shared, versions/v2.13, versions/v2.12, versions/v2.11, versions/v2.10, versions/v2.9, versions/v2.8]
ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./community-supplemental-files
asciidoc:
  attributes:
# product names
    elemental-product-name: "SUSE® Rancher Prime: OS Manager"
    fleet-product-name: "SUSE® Rancher Prime: Continuous Delivery"
    harvester-product-name-tm: "SUSE® Virtualization"
    harvester-product-name: "SUSE Virtualization"
    k3k-product-name: "SUSE Virtual Clusters"
    k3k-product-name-tm: "SUSE® Rancher Prime: Virtual Clusters"
    k3s-product-name: "SUSE® Rancher Prime: K3s"
    kubewarden-product-name: "SUSE Security Admission Controller"
    longhorn-product-name: "SUSE Storage"
    longhorn-product-name-tm: "SUSE® Storage"
    neuvector-product-name: "SUSE® Security"
    # Rancher attributes are soft set (@) so that they can be changed for SRFA
    rancher-short-name: Rancher@
    rke2-product-name: "SUSE® Rancher Prime: RKE2"
    rke2-short-name: "RKE2"
    stackstate-product-name: "SUSE® Observability"
    turtles-product-name: "SUSE® Rancher Prime: Cluster API"
    rancher-prime: Rancher Prime
    rancher-product-name: Rancher
    build-type: community
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
  - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en, zh]
  - require: ./product-docs-common/extensions/versions-latest-prerelease/vlp.js
    enabled: true
output:
  dir: build/site-community-local