site:
  title: SUSE® Rancher Manager
  url: /
  start_page: v2.13@ROOT:ROOT:rancher-manager.adoc
  robots: disallow
content:
  sources: 
  - url: .
    branches: HEAD
    start_paths: [shared, community-docs/v2.13, community-docs/v2.12, community-docs/v2.11, community-docs/v2.10, community-docs/v2.9]
ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./community-supplemental-files
asciidoc:
  attributes:
    build-type: community
    page-pagination: ""
    tabs-sync-option: ""
    # product names
    elemental-product-name: "Elemental"
    fleet-product-name: "Fleet"
    harvester-product-name: "Harvester"
    k3s-product-name: "K3s"
    kubewarden-product-name: "Kubewarden"
    longhorn-product-name: "Longhorn"
    neuvector-product-name: "NeuVector"
    rke2-product-name: "RKE2"
    stackstate-product-name: "SUSE® Observability"
    turtles-product-name: "Turtles"
    rancher-prime: "Rancher"
    rancher-product-name: "Rancher"
    rancher-helm-repo: "rancher-latest"
  extensions:
  - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
  - require: ./product-docs-common/extensions/versions-latest-prerelease/vlp.js
    enabled: true
output:
  dir: build/site-community-local