site:
  title: SUSEÂ® Rancher Manager
  url: /
  start_page: latest@rancher-manager:en:about-rancher/what-is-rancher.adoc
  robots: disallow
content:
  sources: 
  - url: .
    start_paths: [shared, versions/latest, versions/v2.10, versions/v2.9, versions/v2.8]
    branches: HEAD
ui: 
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files
asciidoc:
  attributes:
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
  - '@asciidoctor/tabs'
# antora:
#   extensions:
#   - require: '@antora/lunr-extension'
#     languages: [en, zh]
